import type { WallpaperOption } from '../types/desktop';

// This file is auto-generated by scripts/generate-wallpapers.mjs.
export const wallpaperOptions: WallpaperOption[] = [
  {
    "name": "arch-linux",
    "label": "Arch Linux",
    "imageUrl": "/wallpapers/Arch%20Linux.jpeg"
  },
  {
    "name": "unix",
    "label": "Unix",
    "imageUrl": "/wallpapers/Unix.jpg"
  },
  {
    "name": "windows-10",
    "label": "windows 10",
    "imageUrl": "/wallpapers/windows%2010.jpg"
  },
  {
    "name": "windows-11",
    "label": "Windows 11",
    "imageUrl": "/wallpapers/Windows%2011.png"
  }
];

export const defaultWallpaper = wallpaperOptions[0];
